"""upd

Revision ID: 5767aa04d140
Revises: aa396e8f1a5f
Create Date: 2025-04-27 16:13:57.286478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5767aa04d140'
down_revision: Union[str, None] = 'aa396e8f1a5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bots', sa.Column('proxy', sa.String(), nullable=True))
    op.drop_column('tinder_bots', 'proxy')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tinder_bots', sa.Column('proxy', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('bots', 'proxy')
    # ### end Alembic commands ###
