"""upd

Revision ID: 96561e977741
Revises: 218d001fe617
Create Date: 2025-04-21 22:08:12.730991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96561e977741'
down_revision: Union[str, None] = '218d001fe617'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tinder_bots', sa.Column('dob', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tinder_bots', 'dob')
    # ### end Alembic commands ###
