"""upd

Revision ID: 985b969e805c
Revises: e2d2a6c590a2
Create Date: 2025-04-12 12:28:14.022280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '985b969e805c'
down_revision: Union[str, None] = 'e2d2a6c590a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('thaifriendly_bots_email_key', 'thaifriendly_bots', type_='unique')
    op.drop_column('thaifriendly_bots', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('thaifriendly_bots', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint('thaifriendly_bots_email_key', 'thaifriendly_bots', ['email'])
    # ### end Alembic commands ###
