"""upd

Revision ID: a75e991d6e61
Revises: 96561e977741
Create Date: 2025-04-21 23:01:25.300108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a75e991d6e61'
down_revision: Union[str, None] = '96561e977741'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('thaifriendly_bots_id_fkey', 'thaifriendly_bots', type_='foreignkey')
    op.create_foreign_key(None, 'thaifriendly_bots', 'bots', ['id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('tinder_bots_id_fkey', 'tinder_bots', type_='foreignkey')
    op.create_foreign_key(None, 'tinder_bots', 'bots', ['id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tinder_bots', type_='foreignkey')
    op.create_foreign_key('tinder_bots_id_fkey', 'tinder_bots', 'bots', ['id'], ['id'])
    op.drop_constraint(None, 'thaifriendly_bots', type_='foreignkey')
    op.create_foreign_key('thaifriendly_bots_id_fkey', 'thaifriendly_bots', 'bots', ['id'], ['id'])
    # ### end Alembic commands ###
