"""upd

Revision ID: d2cb1e2c4bf3
Revises: 83f129b99f02
Create Date: 2025-04-12 11:21:32.954662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2cb1e2c4bf3'
down_revision: Union[str, None] = '83f129b99f02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thaifriendly_bots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['bots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.drop_table('thaifriendlybots')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thaifriendlybots',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id'], ['bots.id'], name='thaifriendlybots_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='thaifriendlybots_pkey'),
    sa.UniqueConstraint('email', name='thaifriendlybots_email_key')
    )
    op.drop_table('thaifriendly_bots')
    # ### end Alembic commands ###
