"""upd

Revision ID: e894ee69a951
Revises: bf660a0e1831
Create Date: 2025-04-27 14:34:57.644441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e894ee69a951'
down_revision: Union[str, None] = 'bf660a0e1831'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bots', sa.Column('latitude', sa.Integer(), nullable=True))
    op.add_column('bots', sa.Column('longitude', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bots', 'longitude')
    op.drop_column('bots', 'latitude')
    # ### end Alembic commands ###
