version: "3.9"
services:
  bot:
    build:
      context: ./app
      dockerfile: Dockerfile.bot
    restart: always
    ports:  
      - "8000:8000"
    volumes:
      - ./shared:/app/shared
    depends_on:
      - auth
  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile.auth
    restart: always
    ports:
      - "8001:8001"
    volumes:
      - ./shared:/app/shared
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.client
    restart: always
    ports:
      - "3000:3000"
  nginx:
    image: nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"